permalink: /blog/:year/:month/:day/:title/
timezone: Europe/London

google_analytics_id: UA-4799998-6

available_date: October 2015

markdown: rdiscount

paginate: 10
paginate_path: "blog/page/:num"

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      nav_active: "home"

  -
    scope:
      path: "blog"
      type: "posts"
    values:
      nav_active: "blog"
