name: "Martin Bean"
permalink: /blog/:year/:month/:day/:title/
timezone: Europe/London

author:
  name: Martin Bean
  email: martin@martinbean.co.uk
  uri: http://martinbean.co.uk

google_analytics_id: UA-4799998-6

paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - node_modules
  - CNAME
  - gulpfile.js
  - package.json
  - README.md

highlighter: rogue

collections:
  - talks
