name: Martin Bean
email: "&#x6d;&#97;r&#x74;&#x69;n&#x40;m&#97;&#114;&#x74;&#105;&#110;&#x62;&#101;&#97;n&#46;&#99;&#x6f;.&#117;k"
permalink: /blog/:year/:month/:day/:title/
timezone: Europe/London
url: https://martinbean.dev

disqus_shortname: martinbean
google_analytics_id: UA-4799998-6

paginate: 10
paginate_path: /blog/page/:num

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - bin
  - node_modules
  - vendor
  - Gemfile
  - gulpfile.js
  - package.json
  - README.md

include:
  - _headers
  - _redirects

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      nav: blog
      title_suffix: ' - Blog - Martin Bean'
      upsell: true

current_laravel_version: 9
